test -e ~/.bash_aliases && source ~/.bash_aliases

function __jobs_info {
  local active_jobs=`jobs | wc -l | tr -d ' '`
  test $active_jobs != "0" && echo "[$active_jobs]"
}

PS1="$(tput smul)\u@\h:\w$(__jobs_info)$(tput rmul)$ "

if [ -e ~/.git-completion ]; then
  source ~/.git-completion
fi

export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
export EDITOR=vim
export HISTCONTROL=erasedups
export HISTSIZE=10000
export HISTTIMEFORMAT="%D %T "
export HISTIGNORE="&:ls:exit"
export PROMPT_COMMAND='history -a'
shopt -s histappend

test -f ~/.bash_profile.local && source ~/.bash_profile.local

export PATH="$HOME/.rbenv/bin:$HOME/bin:/usr/local/bin:$PATH"
eval "$(rbenv init -)"
